language: node_js
node_js: ["0.10"]
cache:
  directories:
    - node_modules
    - bower
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install
  - ./node_modules/.bin/bower install
